from .base import SplashBaseItem,SplashImageEmptyFaceItem

splash_items = [
    SplashBaseItem(
        key='taric',
        filename='taric.jpg',
        faceless_filename='taric_faceless.png',
        label='Taric',
        category_key='league_of_legends',
        num_faces=1,
        empty_faces=[
            SplashImageEmptyFaceItem(
                    left=1195,
                    top=80,
                    angle=345,
                    width=155,
                    height=171,
                    label='Taric'
            ),
        ]
    ),
    SplashBaseItem(
        key='yorick',
        filename='yorick.jpg',
        faceless_filename='yorick_faceless.png',
        label='Yorick',
        category_key='league_of_legends',
        num_faces=1,
        empty_faces=[
            SplashImageEmptyFaceItem(
                    left=730,
                    top=60,
                    angle=355,
                    width=90,
                    height=90,
                    label='Yorick'
            ),
        ]
    ),
     SplashBaseItem(
        key='ursula',
        filename='Ursula.jpg',
        faceless_filename='ursula_faceless.png',
        label='Ursula',
        category_key='disney',
        num_faces=1,
        empty_faces=[
            SplashImageEmptyFaceItem(
                    left=493,
                    top=157,
                    angle=1,
                    width=290,
                    height=340,
                    label='Ursula'
            ),
        ]
    ),
     SplashBaseItem(
        key='jinx',
        filename='jinx.jpg',
        faceless_filename='jinx_faceless.png',
        label='Jinx',
        category_key='league_of_legends',
        num_faces=1,
        empty_faces=[
            SplashImageEmptyFaceItem(
                    left=780,
                    top=125,
                    angle=30,
                    width=90,
                    height=82,
                    label='Jinx'
            ),
        ]
    ),
    SplashBaseItem(
        key='darius',
        filename='darius.jpg',
        faceless_filename='darius_faceless.png',
        label='Darius',
        category_key='league_of_legends',
        num_faces=1,
        empty_faces=[
            SplashImageEmptyFaceItem(
                    left=590,
                    top=53,
                    angle=30,
                    width=145,
                    height=145,
                    label='Darius'
            ),
        ]
    ),
    SplashBaseItem(
        key='poppy',
        filename='poppy.jpg',
        faceless_filename='poppy_faceless.png',
        label='Poppy',
        category_key='league_of_legends',
        num_faces=1,
        empty_faces=[
            SplashImageEmptyFaceItem(
                    left=748,
                    top=113,
                    angle=350,
                    width=155,
                    height=140,
                    label='Poppy'
            ),
        ]
    ),
    SplashBaseItem(
        key='gaston',
        filename='gaston.png',
        faceless_filename='gaston_faceless.png',
        label='Gaston',
        category_key='disney',
        num_faces=1,
        empty_faces=[
            SplashImageEmptyFaceItem(
                    left=560,
                    top=137,
                    angle=5,
                    width=160,
                    height=180,
                    label='Gaston'
            ),
        ]
    ),
    SplashBaseItem(
        key='evil-queen-hag',
        filename='evil-queen-hag.png',
        faceless_filename='evil-queen-hag-faceless.png',
        label='Evil Queen (hag)',
        category_key='disney',
        num_faces=1,
        empty_faces=[
            SplashImageEmptyFaceItem(
                    left=410,
                    top=170,
                    angle=13,
                    width=180,
                    height=194,
                    label='Evil Queen'
            ),
        ]
    ),
    SplashBaseItem(
        key='belle',
        filename='belle.jpg',
        faceless_filename='belle-faceless.png',
        label='Belle',
        category_key='disney',
        num_faces=1,
        empty_faces=[
            SplashImageEmptyFaceItem(
                    left=410,
                    top=190,
                    angle=345,
                    width=365,
                    height=410,
                    label='Belle'
            ),
        ]
    ),
    SplashBaseItem(
        key='coco-miguell',
        filename='coco-miguel.jpg',
        faceless_filename='coco-miguel-faceless.png',
        label='Miguel',
        category_key='disney',
        num_faces=1,
        empty_faces=[
            SplashImageEmptyFaceItem(
                    left=490,
                    top=278,
                    angle=10,
                    width=120,
                    height=100,
                    label='Miguel'
            ),
        ]
    ),
    SplashBaseItem(
        key='wreck-it-ralph',
        filename='ralph.png',
        faceless_filename='ralph-faceless.png',
        label='Ralph',
        category_key='disney',
        num_faces=1,
        empty_faces=[
            SplashImageEmptyFaceItem(
                    left=416,
                    top=62,
                    angle=350,
                    width=140,
                    height=140,
                    label='Ralph'
            ),
        ]
    ),
    SplashBaseItem(
        key='vi',
        filename='vi.jpg',
        faceless_filename='vi_faceless.png',
        label='Vi',
        category_key='league_of_legends',
        num_faces=1,
        empty_faces=[
            SplashImageEmptyFaceItem(
                    left=260,
                    top=168,
                    angle=10,
                    width=65,
                    height=65,
                    label='Vi'
            ),
        ]
    ),
]

def get_splash():
    return splash_items
        
